class CFG7:
    VER = 3
    # TRAIN WITH SUBSET OF 60K
    # NUM_TRAIN_SAMPLES = 600000
    # PARAMETER EFFICIENT FINE TUNING
    # PEFT REQUIRES 1XP100 GPU NOT 2XT4
    USE_PEFT = False
    # NUMBER OF LAYERS TO FREEZE
    # DEBERTA LARGE HAS TOTAL OF 24 LAYERS
    FREEZE_LAYERS = 18
    # BOOLEAN TO FREEZE EMBEDDINGS
    FREEZE_EMBEDDINGS = False  # True
    # LENGTH OF CONTEXT PLUS QUESTION ANSWER
    MAX_INPUT = 768  # 384, 768, 1205, 1024
    # HUGGING FACE MODEL
    MODEL = 'model/longformer_qa_model'
    # TRAIN WITH SUBSET OF 60K
    NUM_TRAIN_SAMPLES = 60347  # 50_000
